appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IfKxDPLjkWJU4LcEeebQjO1LmjeySbJ+OKGjUsbPoSNw9i2b4x6p4fzc+eVkZPs8E0C4+a+cfkuMatwJdNcqhK+BtpIvms8uuN6gNVK+N+lpQlu2CpeZCrGhyHp6ve5Oo6z9HrpBZmR9Wle/HQ3Hmzz25x4rk7ebjK5Qhx1wllcJmx9orzMcxu5hSD5bgf/zyQ5aH1f0vjWqR21CZaBtvjamYpP/dVgXFF3vOwbwh+hGNfUduhROwCykMsa1j7ZbB0phjBueG5jNKKf0r7EmF7/AscCouMb9KHs6pAc7CX5HlT/P0Dlvl2+MLiM1ygGLjhtWTnyfDueF9LOvZ+ePx6gqqL1ulHYvPuBUFi6HeqKDoqZ5hyAJCJovljQhrGYTjsxYIj5Ts82Ro052vQRkVGYnXOm655Dp5Db4w7GESKFo4COfv4z9vrCXc7C4IW/NUSFt1DTxQ30IxYpEY2zu0zirh87GU2gMpIrNGKE91VmbNZDmQezgZcpjXmGeVsUov3ve1snD6qUlOAMuX+ZnVR0gYzqv+PiMEV5JIQSGH+uBGkssbkCwsaGA/gnD1AHL4V+Pnp5Ou1PSH2URbmqn/0+sW4YxK5z2yVfyxoAPd/e9HKOjXGAGv0wa9zQRFWR457yRnkdtSfkljZoEh2Ns9I5WtbTm55DVTFVknlvjxNI=
