travis:
  secure:
    BINSTAR_TOKEN: doIHgJhXFUtzdAJNWlQpCyCw53wo+cJE4JyMJDOjqd0+sinKqwdV0wOfez5JqIqLoRDG3F4+OvkumOGJlbaa89oBegvZOgm0N7TnFP18/1CFbMNXrHWIp5l3en84rpxcIGSyesGrRct337LWMG1kW1i3B/QNpFZeCoCXFk/+mqSNI83ElNZe/rUUTbv1ald6pfz+asrUbp635COc/i2mtHw8sSFCBT57oGN2JY4KzOJZN9OIrebipPQmKKKaoRRC4yuc8BgcXKOLjxgw4gzwfHY35FPHxqaEGAvLUJKCeTOl2pDLvvEx+ZN7gCN/a+s1TtvFGbOJDhvR8Xr6w1FIIOby6c1YePUs0slczdTHa4OTrTezSnKs1VRmPaj6NJxcAbIFerD/kGJmjNq+3DDxzy8gNA6/wTuMfwJl4OnmM4UPrXNRV13rf1Jk8CmK5e6UCV+BOfdDGcx3vk2yRS9W65XztrIzfljWp5ZXD/D2Wr+ntNaQDfY58g2PoJBngYlZhOnreW5rdK1RDVE9qIy7Z5HZFNQTJM/kXiXAvWdh/GDpTZUQC8mSbnAdFBvcYWolNh3Pgt9OiSffFF7b4ZkP/v9TFqvKLorW0AV7g5Rrc36G60Nn41HoNJMrpeL4H2/tl5oyKaoWWYuVl3Dge3i39DVpe3sUWkoO9aMBnCrPxOA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
