travis:
  secure:
    BINSTAR_TOKEN: WTYteU/mIJsvGWK4NtJcE1wLVki5k4NNV5H7fovKNng21mU3UeQzHCOok5wcX5EEv5Fio9EjY1fvdWmVt94fG66CS1MSWsHgyjuZ5j2kAphFtSjc1FZhUivxFif7bktGKzU1FWZzV+E/FlXpgaNjTP91W6xGkxU7Nowa3qNnEyKtQI1TxWcPBOvymv9D23cf2gHCStHn5QLNw461HDeNsnMmktOVsVCcPCsB2DIrX3p+x6CR1lS9D6Y2tMVwPIHlwLnhCj6c/R3BpZBw69UZAjlKrEag9Z6OnrvfGktIB8odKXbvFyDX3MI/nWYqSW7I3ijc+74hhJlwrQKCFOeNEBT2dE7fwJbX8P0fl2mZlzp2Or2NHnHcimcnJIjvjwd9LzWkndzuGR6rkKo+TW0Y87UMdMBgg66r0hmCj24p2XCWVND6phf4Kb7ZlN6w1tG9102K0yZ3NIr1xkS/HT8eWRzwE0LMfhjssFb6pQlhTD3w2hA7xP1+aO7JMT0mtCYSxA8iqc8hWo1a9JPoi0nUaW0JBl+LAFiXdGT68NvmxdA1j07Nai8w5atx9ftb5cfrqqZTG15QuFBGtQT3ZsdREWHeMd9Ei/BA8TQMlE4EL1C+PgLoCWakRe1tva3gmYI2NPn91kKCGHJMlzWOVbZdW90zikQzYabQDN4hDhhXLRU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
